name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install RustDesk
      shell: powershell
      run: |
        $ErrorActionPreference = 'Stop'
        .\install_dependencies.ps1
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    - name: Run setup scripts
      shell: powershell
      run: |
        Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        $ErrorActionPreference = 'Stop'
        .\main.ps1
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }