name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run setup scripts
      shell: powershell
      run: Start-Process powershell -ArgumentList '-File .\main.ps1' -Verb RunAs -Wait