name: Deploy RustDesk Server

on: workflow_dispatch

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install RustDesk Server
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri 'https://github.com/rustdesk/rustdesk-server/releases/latest/download/rustdesk-server-windows.zip' -OutFile rustdesk-server.zip
        Expand-Archive -Path rustdesk-server.zip -DestinationPath .\rustdesk-server
        



    - name: Configure Static Credentials
      shell: pwsh
      run: |
        Set-Content -Path .\rustdesk-server\conf\key.txt -Value "${{ inputs.id }}"
        Set-Content -Path .\rustdesk-server\conf\password.txt -Value "Jafar@786"
        
    - name: Run RustDesk Server
      shell: pwsh
      run: |
        $process = Start-Process -FilePath .\rustdesk-server\rustdesk.exe -NoNewWindow -PassThru
        echo "RustDesk process started with PID $($process.Id)"
        Add-Content -Path $env:GITHUB_OUTPUT -Value "process_id=$($process.Id)"
        
    - name: Upload Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: rustdesk-logs
        path: ${{ github.workspace }}\rustdesk-server\logs\*

    - name: Generate Credentials
      id: gen-creds
      shell: pwsh
      run: |
        $id = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 16 | % {[char]$_})
        $password = -join ((33..126) | Get-Random -Count 16 | % {[char]$_})
        echo "ID=$id" >> $env:GITHUB_OUTPUT
        echo "PASSWORD=$password" >> $env:GITHUB_OUTPUT

    outputs:
      rustdesk-id: ${{ steps.gen-creds.outputs.ID }}
      rustdesk-password: ${{ steps.gen-creds.outputs.PASSWORD }}